#server.port= 9130
#Eureka
#eureka.client.registerWithEureka=true
#eureka.client.fetchRegistry=true
#eureka.client.serviceUrl.defaultZone= http://localhost:9110/eureka
#eureka.instance.hostname=localhost
#eureka.instance.prefer-ip-address=true
server:
  port: 9130
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9110/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost
    
      
spring:
  application:
    name: gateway-service
    
  cloud:
    config:
      uri: http://localhost:9120
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true 

  ## API SECURITY WITH KEYCLOAK PROVIDER
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            user-info-authentication-method: header
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          sama-client:
            authorization-grant-type: authorization_code
            client-id: ${app.config.keycloak.client-id}
            client-secret: ${app.config.keycloak.client-secret}
            provider: keycloak
            redirect-uri: http://localhost:8089/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs

## SECURITY BASED CONFIGURATIONS
app:
  config:
    keycloak:
      url: http://localhost:8089/auth
      realm: commune
      client-secret: bf06bc5a-7aaa-44d7-9158-d56dc9ebd405
      client-id: sama-client


