server:
  port: 9130

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9110/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: convention-service
        uri: lb://convention-service
        predicates:
        - Path=/**
        
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/**
    
      
        
      - id: transfer-service
        uri: lb://transfer-service
        predicates:
        - Path=/transfer/**
        filters:
        - RewritePath=/transfer/(?<path>.*), /$\{path}
      - id: account-service
        uri: lb://ACCOUNT-SERVICE
        predicates:
        - Path=/**
        
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: conventions
        url: /v3/api-docs/conventions
      - name: transfer
        url: /v3/api-docs/transfer
      - name: account
        url: /v3/api-docs/account
